version: '1.0'
services:
  postgres:
    image: postgres:13
    environment:
      POSGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
      - ~/:/shared_host
    ports:
      - 5432:5432

  backend:
    restart: on-failure
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../:/app
    depends_on:
      - postgres
    ports:
      - 5000:5000
    command: python manage.py runserver
    environment:
      PYTHONUNBUFFERED: 1
      HOST: 0.0.0.0
      PORT: 5000
      DB_URL: postgresql://postgres:postgres@postgres:5432/postgres
